
about :

  name : 'wTranspile'
  description : 'Aggregator of strategies to transpile JS code. It provides unified programmatic and CL interfaces to transpile/optimize/minimize/beautify code by one or several transpilers in series. More strategies could be added as plugins. Default options of transpilation can be written into a config file to avoid retyping. Use the module to utilize the power of open source transpilation tools in single package.'
  version : '0.4.0'
  enabled : 1
  interpreters :
  - njs >= 10.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools
  - Transpilation
  - transpilation strategies
  - uglify
  - uglify-es
  - uglify-js
  - beautify
  - minify
  - minimize
  - optimize
  - minifier
  - javascript
  - ecmascript
  license : MIT
  author : 'Kostiantyn Wandalen <wanalen@01.school>'
  contributors :
  - 'Kostiantyn Wandalen <wanalen@01.school>'
  npm.name : 'wtranspile'
  npm.scripts :
    test : 'wtest .run proto/**'
    docgen : 'wdocgen .build proto'
    trs : "node proto/dwtools/atop/transpile/entry/Exec"
  npm.bin :
    trs : proto/dwtools/atop/transpile/entry/Exec

path :

  repository : git+https:///github.com/Wandalen/wTranspile.git
  origins :
   - git+https:///github.com/Wandalen/wTranspile.git
   - npm:///wtranspile
  bugtracker : https:///github.com/Wandalen/wTranspile/issues

step :

  proto.export :
    inherit : module.export
    export : path::export
    tar : 0
    criterion :
      content : 'proto'

  doc.export :
    inherit : module.export
    export : path::doc
    tar : 0
    criterion :
      content : 'doc'

  npm.export :
    inherit : module.export
    export : out.npm
    tar : 0
    criterion :
      content : 'npm'

  npm.publish :
    shell : npm publish

build :

  proto.export :
    criterion :
      content : 'proto'
      export : 1
    steps :
      # - build::debug.raw
      - step::proto.export

  doc.export :
    criterion :
      content : 'doc'
      export : 1
    steps :
      # - build::debug.raw
      - step::doc.export

  npm.export :
    criterion :
      content : 'npm'
      export : 1
    steps :
      # - build::debug.raw
      # - step::npm.export
      - step::npm.publish

  export :

    criterion :
      default : 1
      export : 1
    steps :
      # - build::npm
      - build::proto.export
      # - build::doc.export
